development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: northwind_development

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: northwind_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: northwind_prod
